title: Sadam Habnawi Portfolio
description: Data Analyst | Deep Learning | Astrophysics

theme: minima

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages: []
